name: Build and deploy to Azure Container Apps Deploy

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'src/api/**'
      - 'src/web/**'
      - '.github/workflows/depworkflow-fixed.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/api/**'
      - 'src/web/**'
  workflow_dispatch:
    
env:
  # Azure Container Registry details
  AZURE_CONTAINER_REGISTRY: cr3rbky3yz3zumq
  REGISTRY_URL: cr3rbky3yz3zumq.azurecr.io
  
  # Container App Environment
  CONTAINER_APPS_ENVIRONMENT: agent-ca-env
  RESOURCE_GROUP: rg-crtwriter
  
  API_IMAGE_NAME: agent-api3
  WEB_IMAGE_NAME: agent-web3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    #   - uses: actions/checkout@v3
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AGENTAPI2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AGENTAPI2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AGENTAPI2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src/api
          acrName: ${{ env.AZURE_CONTAINER_REGISTRY }}
          containerAppName: ${{ env.API_IMAGE_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppEnvironment: ${{ env.CONTAINER_APPS_ENVIRONMENT }}
          imageToBuild: "${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.API_IMAGE_NAME }}:${SHORT_SHA}"
          dockerfilePath: ${{ github.workspace }}/src/api/Dockerfile